import { PrismaClient } from '../../generated/prisma-primary';

type Row = { device_id: number; command_type_id: number; command: string };
const prisma = new PrismaClient();

const DATA: Row[] = [
  // ===== Device 1: GT06 =====
 { device_id: 1, command_type_id: 1, command: 'STATUS#' },
  { device_id: 1, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 1, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 1, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 1, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 1, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 1, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 1, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 2, command_type_id: 1, command: 'STATUS#' },
  { device_id: 2, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 2, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 2, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 2, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 2, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 2, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 3, command_type_id: 1, command: 'STATUS#' },
  { device_id: 3, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 3, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 3, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 3, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 3, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 3, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 4, command_type_id: 1, command: 'STATUS#' },
  { device_id: 4, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 4, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 4, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 4, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 4, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 4, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 5, command_type_id: 1, command: 'STATUS#' },
  { device_id: 5, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 5, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 5, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 5, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 5, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 5, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 6, command_type_id: 1, command: 'STATUS#' },
  { device_id: 6, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 6, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 6, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 6, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 6, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 6, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 7, command_type_id: 1, command: 'STATUS' },
  { device_id: 7, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 7, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 7, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 7, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 7, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 7, command_type_id: 7, command: 'REBOOT' },
  { device_id: 8, command_type_id: 1, command: 'getver' },
  { device_id: 8, command_type_id: 2, command: 'setparam 2001:{apn};2002:{apnUser};2003:{apnPass}' },
  { device_id: 8, command_type_id: 3, command: 'setparam 3001:{Timer}' },
{ device_id: 8, command_type_id: 4, command: 'setdigout 1 1' },
  { device_id: 8, command_type_id: 5, command: 'setdigout 1 0' },
  { device_id: 8, command_type_id: 6, command: 'setparam 2004:{Device_host_ip};2005:{port}' },
  { device_id: 8, command_type_id: 7, command: 'reboot' },
  { device_id: 9, command_type_id: 1, command: 'check123456' },
  { device_id: 9, command_type_id: 2, command: 'apn123456 {apn} {apnUser} {apnPass}' },
  { device_id: 9, command_type_id: 3, command: 'fix{Timer}s***n123456' },
  { device_id: 9, command_type_id: 4, command: 'stop123456' },
  { device_id: 9, command_type_id: 5, command: 'resume123456' },
  { device_id: 9, command_type_id: 6, command: 'adminip123456 {Device_host_ip} {port}' },
  { device_id: 9, command_type_id: 7, command: 'reset123456' },
  { device_id: 10, command_type_id: 1, command: 'check123456' },
  { device_id: 10, command_type_id: 2, command: 'apn123456 {apn} {apnUser} {apnPass}' },
  { device_id: 10, command_type_id: 3, command: 'fix{Timer}s***n123456' },
  { device_id: 10, command_type_id: 4, command: 'stop123456' },
  { device_id: 10, command_type_id: 5, command: 'resume123456' },
  { device_id: 10, command_type_id: 6, command: 'adminip123456 {Device_host_ip} {port}' },
  { device_id: 10, command_type_id: 7, command: 'reset123456' },
  { device_id: 11, command_type_id: 1, command: 'STATUS#' },
  { device_id: 11, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 11, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 11, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 11, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 11, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 11, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 12, command_type_id: 1, command: 'STATUS#' },
  { device_id: 12, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 12, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 12, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 12, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 12, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 12, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 13, command_type_id: 1, command: 'STATUS#' },
  { device_id: 13, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 13, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 13, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 13, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 13, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 13, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 14, command_type_id: 1, command: 'check123456' },
  { device_id: 14, command_type_id: 2, command: 'apn123456 {apn} {apnUser} {apnPass}' },
  { device_id: 14, command_type_id: 3, command: 'fix{Timer}s***n123456' },
  { device_id: 14, command_type_id: 4, command: 'stop123456' },
  { device_id: 14, command_type_id: 5, command: 'resume123456' },
  { device_id: 14, command_type_id: 6, command: 'adminip123456 {Device_host_ip} {port}' },
  { device_id: 14, command_type_id: 7, command: 'reset123456' },
  { device_id: 15, command_type_id: 1, command: 'STATUS' },
  { device_id: 15, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 15, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 15, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 15, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 15, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 15, command_type_id: 7, command: 'REBOOT' },
    { device_id: 15, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 15, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 15, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 15, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 15, command_type_id: 7, command: 'REBOOT' },
  { device_id: 16, command_type_id: 1, command: 'STATUS#' },
  { device_id: 16, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 16, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 16, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 16, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 16, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 16, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 17, command_type_id: 1, command: 'STATUS' },
  { device_id: 17, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}' },
  { device_id: 17, command_type_id: 3, command: 'TIMER,{Timer}' },
  { device_id: 17, command_type_id: 4, command: 'RELAY,1' },
  { device_id: 17, command_type_id: 5, command: 'RELAY,0' },
  { device_id: 17, command_type_id: 6, command: 'SERVER,1,{Device_host_ip},{port}' },
  { device_id: 17, command_type_id: 7, command: 'REBOOT' },
  { device_id: 18, command_type_id: 1, command: 'check123456' },
  { device_id: 18, command_type_id: 2, command: 'apn123456 {apn} {apnUser} {apnPass}' },
  { device_id: 18, command_type_id: 3, command: 'fix{Timer}s***n123456' },
  { device_id: 18, command_type_id: 4, command: 'stop123456' },
  { device_id: 18, command_type_id: 5, command: 'resume123456' },
  { device_id: 18, command_type_id: 6, command: 'adminip123456 {Device_host_ip} {port}' },
  { device_id: 18, command_type_id: 7, command: 'reset123456' },
  { device_id: 19, command_type_id: 1, command: 'check123456' },
  { device_id: 19, command_type_id: 2, command: 'apn123456 {apn} {apnUser} {apnPass}' },
  { device_id: 19, command_type_id: 3, command: 'fix{Timer}s***n123456' },
  { device_id: 19, command_type_id: 4, command: 'stop123456' },
  { device_id: 19, command_type_id: 5, command: 'resume123456' },
  { device_id: 19, command_type_id: 6, command: 'adminip123456 {Device_host_ip} {port}' },
  { device_id: 19, command_type_id: 7, command: 'reset123456' },
  { device_id: 20, command_type_id: 1, command: 'AT+GVER?' },
  { device_id: 20, command_type_id: 2, command: 'AT+GAPN={apn},{apnUser},{apnPass}' },
  { device_id: 20, command_type_id: 3, command: 'AT+GTFRI=...,{Timer},...' },
  { device_id: 20, command_type_id: 4, command: 'AT+GODO=1,1' },
  { device_id: 20, command_type_id: 5, command: 'AT+GODO=1,0' },
  { device_id: 20, command_type_id: 6, command: 'AT+GSR={Device_host_ip},{port},0' },
  { device_id: 20, command_type_id: 7, command: 'AT+GRST' },
  { device_id: 21, command_type_id: 1, command: 'STATUS#' },
  { device_id: 21, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 21, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 21, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 21, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 21, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 21, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 22, command_type_id: 1, command: 'STATUS#' },
  { device_id: 22, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 22, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 22, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 22, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 22, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 22, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 23, command_type_id: 1, command: 'check123456' },
  { device_id: 23, command_type_id: 2, command: 'apn123456 {apn} {apnUser} {apnPass}' },
  { device_id: 23, command_type_id: 3, command: 'fix{Timer}s***n123456' },
  { device_id: 23, command_type_id: 4, command: 'stop123456' },
  { device_id: 23, command_type_id: 5, command: 'resume123456' },
  { device_id: 23, command_type_id: 6, command: 'adminip123456 {Device_host_ip} {port}' },
  { device_id: 23, command_type_id: 7, command: 'reset123456' },
  { device_id: 24, command_type_id: 1, command: 'STATUS#' },
  { device_id: 24, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 24, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 24, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 24, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 24, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 24, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 25, command_type_id: 1, command: 'STATUS#' },
  { device_id: 25, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 25, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 25, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 25, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 25, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 25, command_type_id: 7, command: 'REBOOT#' },
    { device_id: 22, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 22, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 22, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 22, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 23, command_type_id: 1, command: 'check123456' },
  { device_id: 23, command_type_id: 2, command: 'apn123456 {apn} {apnUser} {apnPass}' },
  { device_id: 23, command_type_id: 3, command: 'fix{Timer}s***n123456' },
  { device_id: 23, command_type_id: 4, command: 'stop123456' },
  { device_id: 23, command_type_id: 5, command: 'resume123456' },
  { device_id: 23, command_type_id: 6, command: 'adminip123456 {Device_host_ip} {port}' },
  { device_id: 23, command_type_id: 7, command: 'reset123456' },
  { device_id: 24, command_type_id: 1, command: 'STATUS#' },
  { device_id: 24, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 24, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 24, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 24, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 24, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 24, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 25, command_type_id: 1, command: 'STATUS#' },
  { device_id: 25, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 25, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 25, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 25, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 25, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 25, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 26, command_type_id: 1, command: 'getver' },
  { device_id: 26, command_type_id: 2, command: 'setparam 2001:{apn};2002:{apnUser};2003:{apnPass}' },
  { device_id: 26, command_type_id: 3, command: 'setparam 3001:{Timer}' },
  { device_id: 26, command_type_id: 4, command: 'setdigout 1 1' },
  { device_id: 26, command_type_id: 5, command: 'setdigout 1 0' },
  { device_id: 26, command_type_id: 6, command: 'setparam 2004:{Device_host_ip};2005:{port}' },
  { device_id: 26, command_type_id: 7, command: 'reboot' },
  { device_id: 27, command_type_id: 1, command: 'getver' },
  { device_id: 27, command_type_id: 2, command: 'setparam 2001:{apn};2002:{apnUser};2003:{apnPass}' },
  { device_id: 27, command_type_id: 3, command: 'setparam 3001:{Timer}' },
  { device_id: 27, command_type_id: 4, command: 'setdigout 1 1' },
  { device_id: 27, command_type_id: 5, command: 'setdigout 1 0' },
  { device_id: 27, command_type_id: 6, command: 'setparam 2004:{Device_host_ip};2005:{port}' },
  { device_id: 27, command_type_id: 7, command: 'reboot' },
  { device_id: 28, command_type_id: 1, command: 'STATUS' },
  { device_id: 28, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 28, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 28, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 28, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 28, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 28, command_type_id: 7, command: 'REBOOT' },
  { device_id: 29, command_type_id: 1, command: 'STATUS' },
  { device_id: 29, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 29, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 29, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 29, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 29, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 29, command_type_id: 7, command: 'REBOOT' },
  { device_id: 30, command_type_id: 1, command: 'STATUS' },
  { device_id: 30, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 30, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 30, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 30, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 30, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 30, command_type_id: 7, command: 'REBOOT' },
    { device_id: 29, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 29, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 29, command_type_id: 7, command: 'REBOOT' },
  { device_id: 30, command_type_id: 1, command: 'STATUS' },
  { device_id: 30, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 30, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 30, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 30, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 30, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 30, command_type_id: 7, command: 'REBOOT' },
  { device_id: 31, command_type_id: 1, command: 'STATUS' },
  { device_id: 31, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}' },
  { device_id: 31, command_type_id: 3, command: 'TIMER,{Timer}' },
  { device_id: 31, command_type_id: 4, command: 'RELAY,1' },
  { device_id: 31, command_type_id: 5, command: 'RELAY,0' },
  { device_id: 31, command_type_id: 6, command: 'SERVER,1,{Device_host_ip},{port}' },
  { device_id: 31, command_type_id: 7, command: 'REBOOT' },
  { device_id: 32, command_type_id: 1, command: 'STATUS#' },
  { device_id: 32, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 32, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 32, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 32, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 32, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 32, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 33, command_type_id: 1, command: 'STATUS' },
  { device_id: 33, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 33, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 33, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 33, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 33, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 33, command_type_id: 7, command: 'REBOOT' },
  { device_id: 34, command_type_id: 1, command: 'STATUS' },
  { device_id: 34, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 34, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 34, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 34, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 34, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 34, command_type_id: 7, command: 'REBOOT' },
  { device_id: 35, command_type_id: 1, command: 'STATUS' },
  { device_id: 35, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 35, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 35, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 35, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 35, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 35, command_type_id: 7, command: 'REBOOT' },
  { device_id: 36, command_type_id: 1, command: 'STATUS' },
  { device_id: 36, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 36, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 36, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 36, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 36, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 36, command_type_id: 7, command: 'REBOOT' },
  { device_id: 37, command_type_id: 1, command: 'STATUS' },
  { device_id: 37, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 37, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 37, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 37, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 37, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 37, command_type_id: 7, command: 'REBOOT' },
  { device_id: 38, command_type_id: 1, command: 'STATUS' },
  { device_id: 38, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 38, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 38, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 38, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 38, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 38, command_type_id: 7, command: 'REBOOT' },
    { device_id: 36, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 36, command_type_id: 7, command: 'REBOOT' },
  { device_id: 37, command_type_id: 1, command: 'STATUS' },
  { device_id: 37, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 37, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 37, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 37, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 37, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 37, command_type_id: 7, command: 'REBOOT' },
  { device_id: 38, command_type_id: 1, command: 'STATUS' },
  { device_id: 38, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 38, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 38, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 38, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 38, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 38, command_type_id: 7, command: 'REBOOT' },
  { device_id: 39, command_type_id: 1, command: 'STATUS' },
  { device_id: 39, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 39, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 39, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 39, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 39, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 39, command_type_id: 7, command: 'REBOOT' },
  { device_id: 40, command_type_id: 1, command: 'STATUS#' },
  { device_id: 40, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 40, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 40, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 40, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 40, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 40, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 41, command_type_id: 1, command: 'STATUS#' },
  { device_id: 41, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 41, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 41, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 41, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 41, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 41, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 42, command_type_id: 1, command: 'AT+GVER?' },
  { device_id: 42, command_type_id: 2, command: 'AT+GAPN={apn},{apnUser},{apnPass}' },
  { device_id: 42, command_type_id: 3, command: 'AT+GTFRI=...,{Timer},...' },
  { device_id: 42, command_type_id: 4, command: 'AT+GODO=1,1' },
  { device_id: 42, command_type_id: 5, command: 'AT+GODO=1,0' },
  { device_id: 42, command_type_id: 6, command: 'AT+GSR={Device_host_ip},{port},0' },
  { device_id: 42, command_type_id: 7, command: 'AT+GRST' },
  { device_id: 43, command_type_id: 1, command: 'STATUS#' },
  { device_id: 43, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 43, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 43, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 43, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 43, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 43, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 44, command_type_id: 1, command: 'STATUS#' },
  { device_id: 44, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 44, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 44, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 44, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 44, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 44, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 45, command_type_id: 1, command: 'STATUS#' },
  { device_id: 45, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 45, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 45, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 45, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 45, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 45, command_type_id: 7, command: 'REBOOT#' },
    { device_id: 43, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 44, command_type_id: 1, command: 'STATUS#' },
  { device_id: 44, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 44, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 44, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 44, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 44, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 44, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 45, command_type_id: 1, command: 'STATUS#' },
  { device_id: 45, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 45, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 45, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 45, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 45, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 45, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 46, command_type_id: 1, command: 'STATUS#' },
  { device_id: 46, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 46, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 46, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 46, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 46, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 46, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 47, command_type_id: 1, command: 'STATUS#' },
  { device_id: 47, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 47, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 47, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 47, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 47, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 47, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 48, command_type_id: 1, command: 'STATUS' },
  { device_id: 48, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 48, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 48, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 48, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 48, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 48, command_type_id: 7, command: 'REBOOT' },
  { device_id: 49, command_type_id: 1, command: 'STATUS#' },
  { device_id: 49, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 49, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 49, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 49, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 49, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 49, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 50, command_type_id: 1, command: 'STATUS#' },
  { device_id: 50, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 50, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 50, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 50, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 50, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 50, command_type_id: 7, command: 'REBOOT#' },
    { device_id: 51, command_type_id: 1, command: 'STATUS#' },
  { device_id: 51, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 51, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 51, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 51, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 51, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 51, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 52, command_type_id: 1, command: 'STATUS#' },
  { device_id: 52, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 52, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 52, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 52, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 52, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 52, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 53, command_type_id: 1, command: 'STATUS#' },
  { device_id: 53, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 53, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 53, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 53, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 53, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 53, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 54, command_type_id: 1, command: 'STATUS#' },
  { device_id: 54, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 54, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 54, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 54, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 54, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 54, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 55, command_type_id: 1, command: 'STATUS#' },
  { device_id: 55, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 55, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 55, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 55, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 55, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 55, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 56, command_type_id: 1, command: 'STATUS#' },
  { device_id: 56, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 56, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 56, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 56, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 56, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 56, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 57, command_type_id: 1, command: 'STATUS#' },
  { device_id: 57, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 57, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 57, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 57, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 57, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 57, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 58, command_type_id: 1, command: 'STATUS#' },
  { device_id: 58, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 58, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 58, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 58, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 58, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 58, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 59, command_type_id: 1, command: 'STATUS#' },
  { device_id: 59, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 59, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 59, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 59, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 59, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 59, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 60, command_type_id: 1, command: 'STATUS#' },
  { device_id: 60, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 60, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 60, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 60, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 60, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 60, command_type_id: 7, command: 'REBOOT#' },
   { device_id: 58, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 58, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 58, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 58, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 58, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 58, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 59, command_type_id: 1, command: 'STATUS#' },
  { device_id: 59, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 59, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 59, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 59, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 59, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 59, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 60, command_type_id: 1, command: 'STATUS#' },
  { device_id: 60, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 60, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 60, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 60, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 60, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 60, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 61, command_type_id: 1, command: 'STATUS' },
  { device_id: 61, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 61, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 61, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 61, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 61, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 61, command_type_id: 7, command: 'REBOOT' },
  { device_id: 62, command_type_id: 1, command: 'getver' },
  { device_id: 62, command_type_id: 2, command: 'setparam 2001:{apn};2002:{apnUser};2003:{apnPass}' },
  { device_id: 62, command_type_id: 3, command: 'setparam 3001:{Timer}' },
  { device_id: 62, command_type_id: 4, command: 'setdigout 1 1' },
  { device_id: 62, command_type_id: 5, command: 'setdigout 1 0' },
  { device_id: 62, command_type_id: 6, command: 'setparam 2004:{Device_host_ip};2005:{port}' },
  { device_id: 62, command_type_id: 7, command: 'reboot' },
  { device_id: 63, command_type_id: 1, command: 'STATUS' },
  { device_id: 63, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 63, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 63, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 63, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 63, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 63, command_type_id: 7, command: 'REBOOT' },
  { device_id: 64, command_type_id: 1, command: 'getver' },
  { device_id: 64, command_type_id: 2, command: 'setparam 2001:{apn};2002:{apnUser};2003:{apnPass}' },
  { device_id: 64, command_type_id: 3, command: 'setparam 3001:{Timer}' },
  { device_id: 64, command_type_id: 4, command: 'setdigout 1 1' },
  { device_id: 64, command_type_id: 5, command: 'setdigout 1 0' },
  { device_id: 64, command_type_id: 6, command: 'setparam 2004:{Device_host_ip};2005:{port}' },
  { device_id: 64, command_type_id: 7, command: 'reboot' },
    { device_id: 65, command_type_id: 3, command: 'setparam 3001:{Timer}' },
  { device_id: 65, command_type_id: 4, command: 'setdigout 1 1' },
  { device_id: 65, command_type_id: 5, command: 'setdigout 1 0' },
  { device_id: 65, command_type_id: 6, command: 'setparam 2004:{Device_host_ip};2005:{port}' },
  { device_id: 65, command_type_id: 7, command: 'reboot' },
  { device_id: 66, command_type_id: 1, command: 'STATUS' },
  { device_id: 66, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 66, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 66, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 66, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 66, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 66, command_type_id: 7, command: 'REBOOT' },
  { device_id: 67, command_type_id: 1, command: 'getver' },
  { device_id: 67, command_type_id: 2, command: 'setparam 2001:{apn};2002:{apnUser};2003:{apnPass}' },
  { device_id: 67, command_type_id: 3, command: 'setparam 3001:{Timer}' },
  { device_id: 67, command_type_id: 4, command: 'setdigout 1 1' },
  { device_id: 67, command_type_id: 5, command: 'setdigout 1 0' },
  { device_id: 67, command_type_id: 6, command: 'setparam 2004:{Device_host_ip};2005:{port}' },
  { device_id: 67, command_type_id: 7, command: 'reboot' },
  { device_id: 68, command_type_id: 1, command: 'STATUS' },
  { device_id: 68, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 68, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 68, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 68, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 68, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 68, command_type_id: 7, command: 'REBOOT' },
  { device_id: 69, command_type_id: 1, command: 'getver' },
  { device_id: 69, command_type_id: 2, command: 'setparam 2001:{apn};2002:{apnUser};2003:{apnPass}' },
  { device_id: 69, command_type_id: 3, command: 'setparam 3001:{Timer}' },
  { device_id: 69, command_type_id: 4, command: 'setdigout 1 1' },
  { device_id: 69, command_type_id: 5, command: 'setdigout 1 0' },
  { device_id: 69, command_type_id: 6, command: 'setparam 2004:{Device_host_ip};2005:{port}' },
  { device_id: 69, command_type_id: 7, command: 'reboot' },
  { device_id: 70, command_type_id: 1, command: 'STATUS#' },
  { device_id: 70, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 70, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 70, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 70, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 70, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 70, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 71, command_type_id: 1, command: 'STATUS#' },
  { device_id: 71, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 71, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 71, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 71, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 71, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 71, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 72, command_type_id: 1, command: 'STATUS#' },
  { device_id: 72, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 72, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 72, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 72, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 72, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 72, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 73, command_type_id: 1, command: 'STATUS' },
  { device_id: 73, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 73, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 73, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 73, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 73, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 73, command_type_id: 7, command: 'REBOOT' },
  { device_id: 74, command_type_id: 1, command: 'STATUS' },
  { device_id: 74, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 74, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 74, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 74, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 74, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 74, command_type_id: 7, command: 'REBOOT' },
  { device_id: 75, command_type_id: 1, command: 'STATUS' },
  { device_id: 75, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 75, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 75, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 75, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 75, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 75, command_type_id: 7, command: 'REBOOT' },
    { device_id: 79, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 79, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 79, command_type_id: 7, command: 'REBOOT' },
  { device_id: 80, command_type_id: 1, command: 'STATUS#' },
  { device_id: 80, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 80, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 80, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 80, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 80, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 80, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 81, command_type_id: 1, command: 'STATUS' },
  { device_id: 81, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 81, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 81, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 81, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 81, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 81, command_type_id: 7, command: 'REBOOT' },
  { device_id: 82, command_type_id: 1, command: 'STATUS' },
  { device_id: 82, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 82, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 82, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 82, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 82, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 82, command_type_id: 7, command: 'REBOOT' },
  { device_id: 83, command_type_id: 1, command: 'STATUS' },
  { device_id: 83, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 83, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 83, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 83, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 83, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 83, command_type_id: 7, command: 'REBOOT' },
  { device_id: 84, command_type_id: 1, command: 'STATUS#' },
  { device_id: 84, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 84, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 84, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 84, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 84, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 84, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 85, command_type_id: 1, command: 'STATUS' },
  { device_id: 85, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 85, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 85, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 85, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 85, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 85, command_type_id: 7, command: 'REBOOT' },
  { device_id: 86, command_type_id: 1, command: 'STATUS' },
  { device_id: 86, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 86, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 86, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 86, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 86, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 86, command_type_id: 7, command: 'REBOOT' },
  { device_id: 87, command_type_id: 1, command: 'STATUS' },
  { device_id: 87, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 87, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 87, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 87, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 87, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 87, command_type_id: 7, command: 'REBOOT' },
  { device_id: 88, command_type_id: 1, command: 'STATUS#' },
  { device_id: 88, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 88, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 88, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 88, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 88, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 88, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 89, command_type_id: 1, command: 'STATUS#' },
  { device_id: 89, command_type_id: 2, command: 'APN,{apn},{apnUser},{apnPass}#' },
  { device_id: 89, command_type_id: 3, command: 'TIMER,{Timer}#' },
  { device_id: 89, command_type_id: 4, command: 'RELAY,1#' },
  { device_id: 89, command_type_id: 5, command: 'RELAY,0#' },
  { device_id: 89, command_type_id: 6, command: 'SERVER,{Device_host_ip},{port}#' },
  { device_id: 89, command_type_id: 7, command: 'REBOOT#' },
  { device_id: 90, command_type_id: 1, command: 'STATUS' },
  { device_id: 90, command_type_id: 2, command: 'APN {apn} {apnUser} {apnPass}' },
  { device_id: 90, command_type_id: 3, command: 'TIMER {Timer}' },
  { device_id: 90, command_type_id: 4, command: 'RELAY 1' },
  { device_id: 90, command_type_id: 5, command: 'RELAY 0' },
  { device_id: 90, command_type_id: 6, command: 'SERVER {Device_host_ip} {port}' },
  { device_id: 90, command_type_id: 7, command: 'REBOOT' },
];

/** Seeder */
export async function seedCustomCommands(client: PrismaClient) {
  await client.customCommand.createMany({
    data: DATA.map(({ device_id, command_type_id, command }) => ({
      deviceTypeId: device_id,
      commandTypeId:command_type_id,
      command,
      isActive: true,
    })),
    // NOTE: For true dedupe, add a unique index in your schema:
    // @@unique([deviceTypeId, commandTypeId, command])
    skipDuplicates: true,
  });
  console.log(`✅ Custom commands seeded: ${DATA.length}`);
}

/** Run standalone */
if (require.main === module) {
  seedCustomCommands(prisma)
    .catch((e) => {
      console.error('❌ Seeding failed:', e);
      process.exitCode = 1;
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}